CREATE TABLE RESTAURANT_ACCOUNT_BANKING(
    ID                  BIGSERIAL,
    EXTERNAL_ID         VARCHAR(26)     NOT NULL,
    RESTAURANT_ID       BIGINT          NOT NULL,
    BANK_CODE           VARCHAR(3)      NOT NULL,
    AGENCY              VARCHAR(5)      NOT NULL,
    ACCOUNT_NUMBER      VARCHAR(20)     NOT NULL,
    VERIFYING_DIGIT     VARCHAR(2)      NOT NULL,
    STATUS              VARCHAR(50)     NOT NULL,
    CREATED_AT          TIMESTAMP       NOT NULL,
    UPDATED_AT          TIMESTAMP       NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RESTAURANT_ACCOUNT_BANKING_RESTAURANT_ID FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
);
CREATE INDEX INDEX_RESTAURANT_ACCOUNT_BANKING__RESTAURANT_ID_STATUS ON RESTAURANT_ACCOUNT_BANKING (RESTAURANT_ID, STATUS);
CREATE UNIQUE INDEX UNIQUE_RESTAURANT_ACCOUNT_BANKING__RESTAURANT_ID ON RESTAURANT_ACCOUNT_BANKING (RESTAURANT_ID) WHERE STATUS = 'ACTIVE';
