CREATE TABLE CUSTOMER
(
    ID          BIGSERIAL,
    EXTERNAL_ID VARCHAR(26)  NOT NULL,
    FIRST_NAME  VARCHAR(200) NOT NULL,
    LAST_NAME   VARCHAR(200) NOT NULL,
    CPF         VARCHAR(11)  NOT NULL,
    EMAIL       VARCHAR(500) NOT NULL,
    BIRTH_DATE  DATE         NOT NULL,
    STATUS      VARCHAR(50)  NOT NULL,
    IMAGE_URL   VARCHAR(1500),
    CREATED_AT  TIMESTAMP    NOT NULL,
    UPDATED_AT  TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_CUSTOMER_EXTERNAL_ID UNIQUE (EXTERNAL_ID)
);

CREATE UNIQUE INDEX UNIQUE_CUSTOMER_CPF ON CUSTOMER (CPF) WHERE STATUS = 'ACTIVE';
CREATE UNIQUE INDEX UNIQUE_CUSTOMER_EMAIL ON CUSTOMER (EMAIL) WHERE STATUS = 'ACTIVE';

CREATE TABLE CUSTOMER_REGISTRATION
(
    ID         BIGSERIAL,
    CUSTOMER_ID   BIGINT      NOT NULL,
    CODE       TEXT        NOT NULL,
    STATUS     VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL,
    UPDATED_AT TIMESTAMP   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTOMER_REGISTRATION_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
    CONSTRAINT UNIQUE_CUSTOMER_REGISTRATION UNIQUE (CUSTOMER_ID)
);

CREATE INDEX UNIQUE_CUSTOMER_REGISTRATION_CUSTOMER_ID ON CUSTOMER_REGISTRATION (CUSTOMER_ID);

CREATE TABLE CUSTOMER_PHONE
(
    ID          BIGSERIAL,
    EXTERNAL_ID VARCHAR(26) NOT NULL,
    CUSTOMER_ID    BIGINT      NOT NULL,
    DDD         VARCHAR(2)  NOT NULL,
    NUMBER      VARCHAR(9)  NOT NULL,
    PHONE_TYPE  VARCHAR(30) NOT NULL,
    CREATED_AT  TIMESTAMP   NOT NULL,
    UPDATED_AT  TIMESTAMP   NOT NULL,
    DELETED_AT  TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTOMER_PHONE_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);

CREATE INDEX INDEX_CUSTOMER_PHONE_CUSTOMER_ID ON CUSTOMER_PHONE (CUSTOMER_ID);
CREATE UNIQUE INDEX UNIQUE_CUSTOMER_PHONE_CUSTOMER_ID ON CUSTOMER_PHONE (CUSTOMER_ID, DDD, NUMBER) WHERE DELETED_AT IS NULL;

CREATE TABLE CUSTOMER_CREDENTIAL
(
    ID         BIGSERIAL,
    CUSTOMER_ID   BIGINT        NOT NULL,
    HASH       VARCHAR(1000) NOT NULL,
    SALT       TEXT          NOT NULL,
    CREATED_AT TIMESTAMP     NOT NULL,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTOMER_CREDENTIAL_EMPLOYEE FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);

CREATE UNIQUE INDEX UNIQUE_CUSTOMER_CREDENTIAL ON CUSTOMER_CREDENTIAL (CUSTOMER_ID) WHERE DELETED_AT IS NULL;
