CREATE TABLE EMPLOYEE
(
    ID              BIGSERIAL,
    EXTERNAL_ID     VARCHAR(26)     NOT NULL,
    RESTAURANT_ID   BIGINT          NOT NULL,
    FIRST_NAME      VARCHAR(200)    NOT NULL,
    LAST_NAME       VARCHAR(200)    NOT NULL,
    CPF             VARCHAR(11)     NOT NULL,
    EMAIL           VARCHAR(500)    NOT NULL,
    BIRTH_DATE      DATE            NOT NULL,
    JOB_FUNCTION    VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(50)     NOT NULL,
    IMAGE_PATH      VARCHAR(1500),
    CREATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_AT      TIMESTAMP       NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_EMPLOYEE_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT FK_EMPLOYEE_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
);

CREATE UNIQUE INDEX UNIQUE_EMPLOYEE_RESTAURANT_ID_CPF ON EMPLOYEE (CPF) WHERE STATUS = 'ACTIVE';
CREATE UNIQUE INDEX UNIQUE_EMPLOYEE_RESTAURANT_ID_EMAIL ON EMPLOYEE (EMAIL) WHERE STATUS = 'ACTIVE';
CREATE INDEX INDEX_EMPLOYEE_RESTAURANT_RESTAURANT_ID ON EMPLOYEE (RESTAURANT_ID);
CREATE INDEX INDEX_EMPLOYEE_RESTAURANT_EMPLOYEE_ID ON EMPLOYEE (EXTERNAL_ID);

CREATE TABLE EMPLOYEE_REGISTRATION
(
    ID          BIGSERIAL,
    EMPLOYEE_ID BIGINT      NOT NULL,
    CODE        TEXT        NOT NULL,
    STATUS      VARCHAR(50) NOT NULL,
    CREATED_AT  TIMESTAMP   NOT NULL,
    UPDATED_AT  TIMESTAMP   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_REGISTRATION_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID),
    CONSTRAINT UNIQUE_EMPLOYEE_REGISTRATION UNIQUE (EMPLOYEE_ID)
);

CREATE INDEX UNIQUE_EMPLOYEE_REGISTRATION_EMPLOYEE_ID ON EMPLOYEE_REGISTRATION (EMPLOYEE_ID);

CREATE TABLE EMPLOYEE_CREDENTIAL
(
    ID          BIGSERIAL,
    EMPLOYEE_ID BIGINT        NOT NULL,
    HASH        VARCHAR(1000) NOT NULL,
    SALT        TEXT          NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL,
    DELETED_AT  TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_CREDENTIAL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID)
);

CREATE UNIQUE INDEX UNIQUE_EMPLOYEE_CREDENTIAL ON EMPLOYEE_CREDENTIAL (EMPLOYEE_ID) WHERE DELETED_AT IS NULL;
