CREATE TABLE RESTAURANT
(
    ID            BIGSERIAL,
    EXTERNAL_ID   VARCHAR(26)       NOT NULL,
    COMPANY_NAME  VARCHAR(1000)     NOT NULL,
    BUSINESS_NAME VARCHAR(1000),
    CNPJ          VARCHAR(14),
    IMAGE_PATH    VARCHAR(1500),
    DDD           VARCHAR(3)        NOT NULL,
    PHONE_NUMBER  VARCHAR(9)        NOT NULL,
    TERM_VERSION  VARCHAR(50),
    TERM_ACCEPTED_BY_EMPLOYEE_ID BIGINT,
    STATUS        VARCHAR(50)       NOT NULL,
    CREATED_AT    TIMESTAMP         NOT NULL,
    UPDATED_AT    TIMESTAMP         NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_RESTAURANT_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT UNIQUE_RESTAURANT_CNPJ UNIQUE (CNPJ)
);

CREATE TABLE RESTAURANT_ADDRESS
(
    ID              BIGSERIAL,
    EXTERNAL_ID     VARCHAR(26)   NOT NULL,
    RESTAURANT_ID   BIGINT        NOT NULL,
    ALIAS_NAME      VARCHAR(100)  NOT NULL,
    STREET          VARCHAR(1000) NOT NULL,
    NUMBER          VARCHAR(10),
    COMPLEMENT      VARCHAR(10),
    CEP             VARCHAR(8)    NOT NULL,
    NEIBORHOOD      VARCHAR(200)  NOT NULL,
    STATE           VARCHAR(2)    NOT NULL,
    CITY            VARCHAR(100)  NOT NULL,
    CREATED_AT      TIMESTAMP     NOT NULL,
    UPDATED_AT      TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RESTAURANT_ADDRESS_RESTAURANT_ID FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID),
    CONSTRAINT UNIQUE_RESTAURANT_ADDRESS_RESTAURANT_ID UNIQUE (RESTAURANT_ID)
);